function createfigure(cdata1, yvector1, data1)
%CREATEFIGURE(cdata1, yvector1, data1)
%  CDATA1:  image cdata
%  YVECTOR1:  bar yvector
%  DATA1:  histogram data

%  Auto-generated by MATLAB on 02-Mar-2023 20:05:00

% Create figure
figure1 = figure;

% Create subplot
subplot1 = subplot(2,2,1);
axis off
hold(subplot1,'on');

% Create image
image(cdata1);

% Create title
title('Imagen a procesar a Color','FontWeight','bold');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot1,[0.5 962.5]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot1,[0.5 574.5]);
box(subplot1,'on');
axis(subplot1,'ij');
hold(subplot1,'off');
% Set the remaining axes properties
set(subplot1,'DataAspectRatio',[1 1 1],'Layer','top','TickDir','out');
% Create subplot
subplot2 = subplot(2,2,2);
axis off
hold(subplot2,'on');

% Create image
image(cdata1);

% Create title
title('Imagen a Procesar a Color','FontWeight','bold');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot2,[0.5 962.5]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot2,[0.5 574.5]);
box(subplot2,'on');
axis(subplot2,'ij');
hold(subplot2,'off');
% Set the remaining axes properties
set(subplot2,'DataAspectRatio',[1 1 1],'Layer','top','TickDir','out');
% Create subplot
subplot3 = subplot(2,2,3);
hold(subplot3,'on');

% Create bar
bar(yvector1,'EdgeColor','none');

% Create title
title(['Histograma "ALGORITMO" ';'Imagen a Color         '],...
    'FontWeight','bold',...
    'FontName','Arial Black',...
    'Color',[0 0 1]);

box(subplot3,'on');
grid(subplot3,'on');
hold(subplot3,'off');
% Create subplot
subplot4 = subplot(2,2,4);
hold(subplot4,'on');

% Create histogram
histogram(data1,'FaceColor',[1 0 0],'BinMethod','auto');

% Create title
title(['Histograma "HISTOGRAM" ';'Imagen a Color         '],...
    'FontWeight','bold',...
    'FontName','Arial Black',...
    'Color',[1 0 0]);

box(subplot4,'on');
grid(subplot4,'on');
hold(subplot4,'off');
% Create line
annotation(figure1,'line',[0.516176470588235 0.515441176470588],...
    [0.995341614906832 0.0357142857142858],'LineWidth',5);

% Create arrow
annotation(figure1,'arrow',[0.745588235294118 0.745588235294118],...
    [0.571981366459627 0.496894409937888],...
    'Color',[0.501960784313725 0.501960784313725 0.501960784313725],...
    'LineWidth',2);

% Create arrow
annotation(figure1,'arrow',[0.297058823529412 0.297058823529412],...
    [0.576639751552795 0.504658385093168],...
    'Color',[0.466666666666667 0.674509803921569 0.188235294117647],...
    'LineWidth',2);

% Create textbox
annotation(figure1,'textbox',...
    [0.422794117647059 0.387198758411852 0.0420937032096557 0.037267080097465],...
    'Color',[0.635294117647059 0.0784313725490196 0.184313725490196],...
    'String',{'  JEVG'},...
    'FontWeight','bold',...
    'FontName','3ds Light');

% Create textbox
annotation(figure1,'textbox',...
    [0.863235294117647 0.38409316834974 0.0420937032096558 0.037267080097465],...
    'Color',[0 0 1],...
    'String',{'  JEVG'},...
    'FontWeight','bold',...
    'FontName','3ds Light');

